name: build-and-release-dagster-hightouch

on:
  push:
    tags:
      - 'dagster_hightouch-*.*.*'

jobs:
  build-and-release-dagster-hightouch:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-hightouch
      working_directory: ./libraries/dagster-hightouch
    secrets: inherit
